name: Terraform AWS EC2 + ALB Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    env:
      TF_VAR_name_prefix: dynamicsite-lb

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working_directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working_directory: terraform

      - name: Terraform Format Check
        run: terraform fmt -check -recursive || true
        working_directory: terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working_directory: terraform

      - name: Run Checkov (informative)
        run: |
          checkov -d . --framework terraform --exit-code 0 || true
          echo "checkov-completed=true" >> $GITHUB_OUTPUT
        working_directory: terraform

      - name: Upload Checkov Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: checkov-report.json

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve tfplan
        working_directory: terraform

  terraform-destroy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      TF_VAR_name_prefix: dynamicsite-lb
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working_directory: terraform